### PR TITLE
Added a test, that verifies that the URCap can be used with a driver

### PR DESCRIPTION
**Pull request by urmahp**
These changes will test that the URCap can be used in a robot program together with a driver.

Added a container running a UR simulator and a container running the client library. The test is added to the container with the client library and executed inside this container, as the test requires the client library in order to work.

### CODE REVIEW

**Comment by fmauch** [comment]
I'ts been a while not answering this... Should we migrate this to use the official URSim docker image instead?

**Comment by urmahp** [comment]
That's a good idea. I will update the PR, so that it makes use of the official URSim instead.

**Comment by urmahp** [comment]
Updated the PR to make use of the image from dockerhub. Also we could make use of the script in #22 to test the URCap, instead of depending on the client library. This can be done once the other PR has been merged.

**Comment by fmauch** [comment]
> Updated the PR to make use of the image from dockerhub. Also we could make use of the script in #22 to test the URCap, instead of depending on the client library. This can be done once the other PR has been merged.

I like that idea.

**Comment by fmauch** [comment]
@urmahp would you like to address https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap/pull/19#issuecomment-1031527418 now that #22 is merged?

**Comment by urmahp** [comment]
> @urmahp would you like to address [#19 (comment)](https://github.com/UniversalRobots/Universal_Robots_ExternalControl_URCap/pull/19#issuecomment-1031527418) now that #22 is merged?

Yes I will try to see if I can have a look at it next week.

**Comment by urmahp** [comment]
> @urmahp just a small reminder: Do we want to finish this any time soon?

As far as I remember it should be finished, but i will have a look at it today.

**Comment by fmauch** [comment]
Didn't we want to change this to use the official docker image?

**Comment by urmahp** [comment]
I gave it a quick look. It has been finished and is just missing a review :-)

**Pull request merged**
